# NeON build file (http://github.com/c4s4/neon)

extends: slides
expose:  [slides, publish, release, examples, TITLE, OPTIONS]
default: [clean, examples, publish]
configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

properties:
  TITLE:   'Go Generics'
  #OPTIONS: '{ratio: "4:3"}'
  OPTIONS: "{ratio: '16:9'}"
  INCLUDES: true

targets:

  examples:
    doc: "Run code examples"
    steps:
    - for: file
      in:  'find(".", "**/*.go")'
      do:
      - print: "######################### Running ={file} #########################"
      - $: ['go', 'run', =file]
